<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;

class UserSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    User::create(['first_name' => 'ZAYDEE', 'middle_name' => 'ECO', 'last_name' => 'MEDINA', 'extension_name' => '', 'email' => 'zaeco@dswd.gov.ph', 'gender' => 'FEMALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'ZAIDE', 'middle_name' => 'BAJAO', 'last_name' => 'ALQUIZAR', 'extension_name' => '', 'email' => 'zaide0227@gmail.com', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'GODWIN', 'middle_name' => 'AGTING', 'last_name' => 'ZAMORA', 'extension_name' => '', 'email' => 'zamzam.gz16@gmail.com', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'ZANDRO', 'middle_name' => 'BANAL', 'last_name' => 'RABANES', 'extension_name' => '', 'email' => 'zandrorabanes@gmail.com', 'gender' => 'MALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'ZARIENA EVA', 'middle_name' => 'CABILES', 'last_name' => 'BAGA', 'extension_name' => '', 'email' => 'zarienaevs23@gmail.com', 'gender' => 'FEMALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'ZAYDEE', 'middle_name' => 'ASPECTO', 'last_name' => 'ECO', 'extension_name' => '', 'email' => 'zayd85_libra@yahoo.com', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'ZARAH DONNA', 'middle_name' => 'SAUBON', 'last_name' => 'DOMINGO', 'extension_name' => '', 'email' => 'zdsdomingo@dswd.gov.ph', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'ZEINB MOHD IJAS', 'middle_name' => 'CEPEDA', 'last_name' => 'NAZAR', 'extension_name' => '', 'email' => 'zeinb.nazar@gmail.com', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'ZENITH VIA', 'middle_name' => 'BUSALANAN', 'last_name' => 'PANDORO', 'extension_name' => '', 'email' => 'zenithpandoro07@gmail.com', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'FREDILIM', 'middle_name' => 'USI', 'last_name' => 'ISIP', 'extension_name' => '', 'email' => 'zennymax19@gmail.com', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'RONNEL', 'middle_name' => 'PANUGAN', 'last_name' => 'MASAGLANG', 'extension_name' => '', 'email' => 'Zeroninenetyone@gmail.com', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'VEZEL JEAN', 'middle_name' => 'AMBASAN', 'last_name' => 'LIM', 'extension_name' => '', 'email' => 'zhel061498@gmail.com', 'gender' => 'FEMALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'LYNETH', 'middle_name' => 'BALDOMERO', 'last_name' => 'LAGUMBAY', 'extension_name' => '', 'email' => 'zioneth_12@yahoo.com', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'ZENITH', 'middle_name' => 'MONTEJO', 'last_name' => 'MANAN', 'extension_name' => '', 'email' => 'zjmmanan@gmail.com', 'gender' => 'FEMALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'JOAN', 'middle_name' => 'GALLENTES', 'last_name' => 'PACHECO', 'extension_name' => '', 'email' => 'zyannfaith.12@gmail.com', 'gender' => 'FEMALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'ZYDEE', 'middle_name' => 'HILAY', 'last_name' => 'LANGUIDO', 'extension_name' => '', 'email' => 'zydeelanguido13@gmail.com', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'ZYRA  MAE', 'middle_name' => 'DELLOMES', 'last_name' => 'SU-AY', 'extension_name' => '', 'email' => 'ZYRASUAY@GMAIL.COM', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'MARIA', 'middle_name' => 'QUIBING', 'last_name' => 'MOSTERO', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'MAE', 'middle_name' => 'PASCUAL', 'last_name' => 'VALENTIN', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SEPARATED']);
    User::create(['first_name' => '', 'middle_name' => '', 'last_name' => '', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JULE', 'middle_name' => 'ANCHETA', 'last_name' => 'ANTIOLA', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'EDNA VENANCIA', 'middle_name' => 'CONCEPCION', 'last_name' => 'MANIMOG', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'ANNIE', 'middle_name' => 'LONGQUIAS', 'last_name' => 'ALLIT', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'JOHN CHRISTIAN', 'middle_name' => 'LONZON', 'last_name' => 'DUMALAGAN', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'JANE', 'middle_name' => 'ABEAR', 'last_name' => 'PARCON', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'WIDOWED']);
    User::create(['first_name' => 'EMELDA', 'middle_name' => 'VILLAFANE', 'last_name' => 'FORRO', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'MIGUEL PAOLO ANGELO', 'middle_name' => 'BATOY', 'last_name' => 'GASCON', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'JENNIFER', 'middle_name' => 'CENTINA', 'last_name' => 'PEÑAFLORIDA', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'MERLINA', 'middle_name' => 'LLOREN', 'last_name' => 'PON', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'LEAH', 'middle_name' => 'SERANO', 'last_name' => 'CACHUELA', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'RAFFY JAMES', 'middle_name' => 'TIMON', 'last_name' => 'VILLACORTA', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'LINDEN FAITH', 'middle_name' => 'BANLUTA', 'last_name' => 'LANTACO', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'VARNELL', 'middle_name' => 'MANDAGWAY', 'last_name' => 'DAGANSAN', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'KEVIN JOSEPH', 'middle_name' => 'GINGOYON', 'last_name' => 'VILLAROJO', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'BELHAREN', 'middle_name' => 'SHIROMA', 'last_name' => 'CAMACHO', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'RANDY', 'middle_name' => 'SULIT', 'last_name' => 'EBON', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'LAARNEE', 'middle_name' => 'QUEZON', 'last_name' => 'IBITA', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'EDILBERTO', 'middle_name' => 'DIOSO', 'last_name' => 'GUERZON', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'BERNARD', 'middle_name' => 'MASCARIÑAS', 'last_name' => 'BARAO', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'ROSELYN', 'middle_name' => 'TIPON', 'last_name' => 'TURTUR', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'MERCY', 'middle_name' => 'BUCOYLA', 'last_name' => 'SAMPIANO', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'GRETCHEN', 'middle_name' => 'POLINAR', 'last_name' => 'ANDIGAN', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'JENIFE', 'middle_name' => 'BELLO', 'last_name' => 'MINTED', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'JOHN MARK', 'middle_name' => 'PORMIENTO', 'last_name' => 'IGUIANON', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'ARJENETH', 'middle_name' => 'SEROHIJOS', 'last_name' => 'ADAPTAR', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'GRACE', 'middle_name' => 'RIVERO', 'last_name' => 'NESPEROS', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'POPJEWISH', 'middle_name' => 'FERNANDEZ', 'last_name' => 'PAQUEO', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'BREN MAE', 'middle_name' => 'BALDERAS', 'last_name' => 'ALAMBATIN', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'FERNANDO', 'middle_name' => 'FANO', 'last_name' => 'ADLAO', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'WIDOWED']);
    User::create(['first_name' => 'JOBEL KRISMA BEANCA', 'middle_name' => 'TANILON', 'last_name' => 'BELDERA', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'NOR-AINE', 'middle_name' => 'ARELLANO', 'last_name' => 'SANAMA', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'VANESSA', 'middle_name' => 'PILAPIL', 'last_name' => 'LAYASAN', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'ETTA JONALYN', 'middle_name' => 'CARDINES', 'last_name' => 'DECENA', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'ALAIN CARLO', 'middle_name' => 'DE LEON', 'last_name' => 'JUMAWAN', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'ALVIN', 'middle_name' => 'MARGALLO', 'last_name' => 'BORJA', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'ALBERT', 'middle_name' => 'LETADA', 'last_name' => 'BUGAYONG', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'MYRA NATHALIE', 'middle_name' => 'VILLAPAÑA', 'last_name' => 'LIM', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'NORWENA', 'middle_name' => 'LIGUEZ', 'last_name' => 'CABALUD', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'MARK JOSEPH', 'middle_name' => 'PALER', 'last_name' => 'LLEMIT', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'ANA', 'middle_name' => 'AMBOG', 'last_name' => 'ADANG', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => '', 'middle_name' => '', 'last_name' => '', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'GRACE', 'middle_name' => 'MONARES', 'last_name' => 'GUITGUIT', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => '', 'middle_name' => '', 'last_name' => '', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'SHIRLEY MAE', 'middle_name' => 'ARAT', 'last_name' => 'COMAR', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'JULIE ANNE MARIE', 'middle_name' => 'GUMATAY', 'last_name' => 'PIEDAD', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'DAISY JOY', 'middle_name' => 'SANTARIN', 'last_name' => 'MEÑOLAS', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'MICHAEL JOHN', 'middle_name' => 'BISARES', 'last_name' => 'SORDILLO', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'LEA MAE', 'middle_name' => 'ANDO', 'last_name' => 'LAPAZ', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'JAKELOU', 'middle_name' => 'CAMPOREDONDO', 'last_name' => 'RODAJE', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'ERWIN', 'middle_name' => 'SUMILE', 'last_name' => 'DEL ROSARIO', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'WALTER JR.,', 'middle_name' => 'TUMABANG', 'last_name' => 'RONDEZ', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'JANET', 'middle_name' => 'GENOVIS', 'last_name' => 'MANAYTAY', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'CHARMAINE', 'middle_name' => 'ARAT', 'last_name' => 'AMPIT', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'JOHN', 'middle_name' => 'PALER', 'last_name' => 'LLEMIT', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'CRYSTAL PEARL', 'middle_name' => 'FALLORINA', 'last_name' => 'GASCON', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'DYAN MARY JOY', 'middle_name' => 'AÑASCO', 'last_name' => 'NESPEROS', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'EFREYLYN', 'middle_name' => 'MAMALIA', 'last_name' => 'COMALING', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'ROJAN MIE', 'middle_name' => 'INSO', 'last_name' => 'PANUNCIALMAN', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'RHEY', 'middle_name' => 'ALINTON', 'last_name' => 'RELLON', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'RAMEL', 'middle_name' => 'CARCUEBA', 'last_name' => 'COLANAG', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'RENTY LOUISE', 'middle_name' => 'ANCAJAS', 'last_name' => 'GAZO', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'ISABEL', 'middle_name' => 'CABARRUBIAS', 'last_name' => 'ESCURZON', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'CANDELARIO', 'middle_name' => 'LOMARDA', 'last_name' => 'SERAFICA', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'MYRA MANUELA', 'middle_name' => 'MATEO', 'last_name' => 'PILAR', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'ROLANDO', 'middle_name' => 'MALICAY', 'last_name' => 'URGEL', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'GRACE', 'middle_name' => 'Q', 'last_name' => 'SUBONG', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'JENIFE', 'middle_name' => 'MINTED', 'last_name' => 'PASCIOLES', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'JOHN LAURENCE', 'middle_name' => 'SUMAMBOT', 'last_name' => 'BAYON', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'IVAN HOWELL', 'middle_name' => 'REYES', 'last_name' => 'MARTINEZ', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'LEAN JEAN', 'middle_name' => '', 'last_name' => 'BAGAY', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'MARK LOU', 'middle_name' => 'CUIZON', 'last_name' => 'AMISTAD', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'JUBABE', 'middle_name' => 'CAYETANO', 'last_name' => 'SABORNIDO', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'AVON KRESTA', 'middle_name' => 'BOTES', 'last_name' => 'NICOSA', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'MARIA ANA', 'middle_name' => 'LUMANGTAD', 'last_name' => 'TAKEUCHI', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'PAUL DENNIS', 'middle_name' => 'PALMA', 'last_name' => 'PARIAN', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'RICHARD', 'middle_name' => 'MANINGO', 'last_name' => 'DE PERIO', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'WELRINA EUNICE', 'middle_name' => 'SIMBAJON', 'last_name' => 'MAHINAY', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'CARLO JACK', 'middle_name' => 'LINANTOD', 'last_name' => 'PINO', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'DIANNE ROSE', 'middle_name' => 'DIANITO', 'last_name' => 'MISAGAL', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'REINER REY  ', 'middle_name' => 'ECHAVEZ', 'last_name' => 'VALENZUELA', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'JESS ANTHONY', 'middle_name' => 'PERALTA', 'last_name' => 'ALCID', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'HERLEN JANE', 'middle_name' => 'LLUP', 'last_name' => 'FELISILDA', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'CAMILLE', 'middle_name' => 'CUA', 'last_name' => 'BELANISO', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'NARNO', 'middle_name' => 'SUPERALES', 'last_name' => 'PUTONG', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'STELLA MARIE', 'middle_name' => 'AMAY', 'last_name' => 'SINGOC', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'ROLLY', 'middle_name' => 'DEVILA', 'last_name' => 'LIANDA', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'JOHN PAUL', 'middle_name' => 'DELA CRUZ', 'last_name' => 'MARTINEZ', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'ROD ELDON G.', 'middle_name' => 'GARCIA', 'last_name' => 'ULANDAY', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'FIDES B', 'middle_name' => 'BRIONES', 'last_name' => 'FERNANDEZ', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'ANGELO', 'middle_name' => 'MANIMBO', 'last_name' => 'PASCUAL', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'GERARD', 'middle_name' => 'DEL ROSARIO', 'last_name' => 'DELOS REYES', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'JANESYN', 'middle_name' => 'GULTIANO', 'last_name' => 'CABO', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'LEA', 'middle_name' => 'D', 'last_name' => 'ARELLANO', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'MARLON', 'middle_name' => 'C', 'last_name' => 'ANGANA', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'HONEY  MAE', 'middle_name' => 'GUILARAN', 'last_name' => 'CAHULOGAN', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'MILYN', 'middle_name' => 'B', 'last_name' => 'CAWALING', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'ANGEL MAE', 'middle_name' => 'C', 'last_name' => 'MULIT', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'CRISANTO', 'middle_name' => 'B', 'last_name' => 'PANOY', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'KINJOVELL', 'middle_name' => 'M', 'last_name' => 'PORMENTO', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'ELAINE', 'middle_name' => 'B', 'last_name' => 'SEDURANTE', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'RHEA', 'middle_name' => 'JIPUS', 'last_name' => 'CUNANAN', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'ERIC', 'middle_name' => 'UGMAD', 'last_name' => 'DIAZ', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'MAR DINCENT', 'middle_name' => 'LADERA', 'last_name' => 'SALASINAS', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'RONELYN MAY', 'middle_name' => 'Y', 'last_name' => 'ENALAMAN', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'JETHRO', 'middle_name' => 'DELA CRUZ', 'last_name' => 'CHU', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'ROY', 'middle_name' => 'ASCARES', 'last_name' => 'QUEZADA', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'LOVELY ROSE', 'middle_name' => 'CAVITE', 'last_name' => 'RACHO', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'KIANA', 'middle_name' => 'M', 'last_name' => 'CORNEJO', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'ANGELO', 'middle_name' => 'CABAÑERO', 'last_name' => 'DEDICATORIA', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'JONIPHER', 'middle_name' => 'GAMAYOT', 'last_name' => 'MIASE', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'SWITZEL', 'middle_name' => 'MAYBUENA', 'last_name' => 'ABAYA', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'JOCELYN', 'middle_name' => 'SAMBURAYAN', 'last_name' => 'ADIMAT', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'CHRISTIAN JAY', 'middle_name' => 'GONZAGA', 'last_name' => 'AMOGUIS', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'NOR-AIN', 'middle_name' => 'SULTAN', 'last_name' => 'AMORAN', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'JAMESON', 'middle_name' => 'LOMARDA', 'last_name' => 'AÑORA', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'LORYFE', 'middle_name' => 'HEYRES', 'last_name' => 'BUNAC', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'MOHAMEL JANE', 'middle_name' => 'ASTANG', 'last_name' => 'CHIQUITO', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'JONATHAN', 'middle_name' => 'SAVELLA', 'last_name' => 'COSTAÑOS', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'JESSA MICHAELA', 'middle_name' => 'TINTIO', 'last_name' => 'DAGOHOY', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'WILLIAM', 'middle_name' => 'REYES', 'last_name' => 'EDUAGIN', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'SHARMIL KAYE', 'middle_name' => 'GERODIAS', 'last_name' => 'GALONO', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'ANGEL FAITH', 'middle_name' => 'CASTRO', 'last_name' => 'GOMEZ', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'YENOH NNEL', 'middle_name' => 'G', 'last_name' => 'LOPEZ', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'MAR DINCENT', 'middle_name' => 'LADERA', 'last_name' => 'SALISINAS', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'CARMELLA JOY', 'middle_name' => 'MACAVINTA', 'last_name' => 'DELA CRUZ', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'SAMUEL', 'middle_name' => 'P', 'last_name' => 'CASTARDO', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'KRISTELEEN', 'middle_name' => 'EDU', 'last_name' => 'RALA', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'CONCHITA', 'middle_name' => 'MARIANO', 'last_name' => 'PELAYRE', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'RUEL JAY', 'middle_name' => 'POSTRANO', 'last_name' => 'GRAZA', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'JADE DAVEN', 'middle_name' => 'BARRAL', 'last_name' => 'GENJORAN', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'MARIONELIZ', 'middle_name' => 'D', 'last_name' => 'PAYAS', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'SHAJANIE LYN', 'middle_name' => 'SECLAYAN', 'last_name' => 'MENDEZ', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'NINO BRYAN', 'middle_name' => 'TALIBONG', 'last_name' => 'ACERO', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'WILLIAM', 'middle_name' => 'REYES', 'last_name' => 'EDUAGIN', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'JENILYN', 'middle_name' => 'R', 'last_name' => 'ALCARIA', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'JOHN MARK', 'middle_name' => 'PORMEINTO', 'last_name' => 'IGUIANON', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'LANI', 'middle_name' => 'MARTIZANO', 'last_name' => 'SAN JUAN', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'LEN MARJORIE', 'middle_name' => 'TENORIO', 'last_name' => 'LUPO', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'RUSSEL', 'middle_name' => 'HERMOSILLA', 'last_name' => 'MAMAC', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'MARIA', 'middle_name' => 'MONTOYA', 'last_name' => 'REPAREJO', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'VINAGIN', 'middle_name' => 'LOGUINSA', 'last_name' => 'LIGUEZ', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'NOVERLYN', 'middle_name' => 'AGUILAR', 'last_name' => 'PARAME', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'MAE', 'middle_name' => 'PAGULA', 'last_name' => 'PASCUAL', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'CHERRY MAE', 'middle_name' => 'PRICE', 'last_name' => 'SUNGA', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'CHRISTINE', 'middle_name' => 'NAVARRO', 'last_name' => 'BATIAO', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'MOHAMEL JANE', 'middle_name' => 'ASTANG', 'last_name' => 'CHIQUITO', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'JENILYN', 'middle_name' => 'RIVERA', 'last_name' => 'ALCARIA', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'JAMESON', 'middle_name' => 'LOMARDA', 'last_name' => 'ANORA', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'ABNER', 'middle_name' => 'LAUNIO', 'last_name' => 'LUNA', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'WENDY PEARL JOY', 'middle_name' => 'COMPENDIO', 'last_name' => 'CABALLERO', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => '']);
    User::create(['first_name' => 'ROWE', 'middle_name' => 'SOLIMAN', 'last_name' => 'TAYONGTONG', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'CHRISTIAN JAY', 'middle_name' => 'GONZAGA', 'last_name' => 'AMOGUIS', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'DIVINE', 'middle_name' => 'CONOL', 'last_name' => 'NEPOMUCENO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'SARAH MARI', 'middle_name' => 'CAPURAS', 'last_name' => 'ALDAO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'SARAH MARI', 'middle_name' => 'CAPURAS', 'last_name' => 'ALDAO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'NAIFA', 'middle_name' => 'DIKI', 'last_name' => 'MANDING', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'NAIFAH', 'middle_name' => 'DIKI', 'last_name' => 'MANDING', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'NAIFAH', 'middle_name' => 'DIKI', 'last_name' => 'MANDING', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ANNALYN', 'middle_name' => 'BALAIS', 'last_name' => 'BINONDO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'GHENE HENRY', 'middle_name' => 'NARIDO', 'last_name' => 'CANIA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ROSALIE', 'middle_name' => 'BULAHAN', 'last_name' => 'VELASCO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'CLAIRE MARIE', 'middle_name' => 'BALURAN', 'last_name' => 'JARDELIZA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'KIARA JEAN', 'middle_name' => 'ARANAS', 'last_name' => 'MARIMON', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'VANESSA', 'middle_name' => 'BACUS', 'last_name' => 'GOC-ONG', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'SHIELA MAE', 'middle_name' => 'VILLAROQUE', 'last_name' => 'GABUYA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'TREXIA VALLERY', 'middle_name' => 'BIORE', 'last_name' => 'TAPIA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'SHEILA', 'middle_name' => 'ABRAHAN', 'last_name' => 'ASOQUE', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MARITES', 'middle_name' => 'FELIPE', 'last_name' => 'SALVADOR', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'ELLEN MARIEL', 'middle_name' => 'SOMBADON', 'last_name' => 'MASLOG', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ARGIE', 'middle_name' => 'ANG', 'last_name' => 'ABELLANOSA', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'JEANETH', 'middle_name' => 'NAPULAG', 'last_name' => 'BAJA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JERELYN', 'middle_name' => 'LIBRE', 'last_name' => 'BARO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JERELYN', 'middle_name' => 'LIBRE', 'last_name' => 'BARO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JERELYN', 'middle_name' => 'LIBRE', 'last_name' => 'BARO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JERELYN', 'middle_name' => 'LIBRE', 'last_name' => 'BARO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JERELYN', 'middle_name' => 'LIBRE', 'last_name' => 'BARO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'BREN MAE', 'middle_name' => 'BALDERAS', 'last_name' => 'ALAMBATIN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'BREN MAE', 'middle_name' => 'BALDERAS', 'last_name' => 'ALAMBATIN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'BREN MAE', 'middle_name' => 'BALDERAS', 'last_name' => 'ALAMBATIN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'GRETCHEN', 'middle_name' => 'POLINAR', 'last_name' => 'ANDIGAN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'GRETCHEN', 'middle_name' => 'POLINAR', 'last_name' => 'ANDIGAN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'BREN MAE', 'middle_name' => 'BALDERAS', 'last_name' => 'ALAMBATIN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'EMILY JOY', 'middle_name' => 'BRETANIA', 'last_name' => 'ANDUYAN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MAEGAN', 'middle_name' => 'BALANTE', 'last_name' => 'TOMANGGONG', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MAEGAN', 'middle_name' => 'BALANTE', 'last_name' => 'TOMANGGONG', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MAEGAN', 'middle_name' => 'BALANTE', 'last_name' => 'TOMANGGONG', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MAEGAN', 'middle_name' => 'BALANTE', 'last_name' => 'TOMANGGONG', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MAEGAN', 'middle_name' => 'BALANTE', 'last_name' => 'TOMANGGONG', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MAEGAN', 'middle_name' => 'BALANTE', 'last_name' => 'TOMANGGONG', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MAEGAN', 'middle_name' => 'BALANTE', 'last_name' => 'TOMANGGONG', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JERELYN', 'middle_name' => 'LIBRE', 'last_name' => 'BARO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JERELYN', 'middle_name' => 'LIBRE', 'last_name' => 'BARO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JERELYN', 'middle_name' => 'LIBRE', 'last_name' => 'BARO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JERELYN', 'middle_name' => 'LIBRE', 'last_name' => 'BARO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'BREN MAE', 'middle_name' => 'BALDERAS', 'last_name' => 'ALAMBATIN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'BREN MAE', 'middle_name' => 'BALDERAS', 'last_name' => 'ALAMBATIN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'BREN MAE', 'middle_name' => 'BALDERAS', 'last_name' => 'ALAMBATIN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'CECILLE', 'middle_name' => 'HOYLAR', 'last_name' => 'HAVANA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'CECILLE', 'middle_name' => 'HOYLAR', 'last_name' => 'HAVANA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'CECILLE', 'middle_name' => 'HOYLAR', 'last_name' => 'HAVANA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MARIEL', 'middle_name' => 'REUTEREZ', 'last_name' => 'LEOPOLDO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MARIEL', 'middle_name' => 'REUTEREZ', 'last_name' => 'LEOPOLDO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MARIEL', 'middle_name' => 'REUTEREZ', 'last_name' => 'LEOPOLDO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ROSEMARIE MAE', 'middle_name' => 'PLENOS', 'last_name' => 'LIGUTAN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JERELYN', 'middle_name' => 'LIBRE', 'last_name' => 'BARO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JERELYN', 'middle_name' => 'LIBRE', 'last_name' => 'BARO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'FE', 'middle_name' => 'MANGANTANG', 'last_name' => 'DIOMALA', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'DULCE', 'middle_name' => 'TABOR', 'last_name' => 'LOSBANES', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'DULCE', 'middle_name' => 'TABOR', 'last_name' => 'LOSBANES', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ALANG', 'middle_name' => 'ALANG', 'last_name' => 'ALANG', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ALANG', 'middle_name' => 'ALANG', 'last_name' => 'ALANG', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'NOBA JESSA', 'middle_name' => 'SABADOQUIA', 'last_name' => 'LOPEZ', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'WILLIAM', 'middle_name' => 'REYES', 'last_name' => 'EDUAGIN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JERELYN', 'middle_name' => 'M', 'last_name' => 'BARO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JERELYN', 'middle_name' => 'M', 'last_name' => 'BARO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'CARLO JACK', 'middle_name' => 'L', 'last_name' => 'PINO', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'LEA', 'middle_name' => 'DILLA', 'last_name' => 'ARELLANO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'GEMMA', 'middle_name' => 'CAMISO', 'last_name' => 'PLAZA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'GAY MARIE', 'middle_name' => 'GABATO', 'last_name' => 'BURLAOS', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JOSEPH', 'middle_name' => 'MARTIZANO', 'last_name' => 'ILLUSTRISIMO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'EDNIE', 'middle_name' => 'CANOY', 'last_name' => 'INFIESTO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'RECHELLYN ANN', 'middle_name' => 'TAMPOS', 'last_name' => 'LABARCON', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MERASUL', 'middle_name' => 'LAIDAN', 'last_name' => 'ALQUIZAR', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ORVEN PAUL', 'middle_name' => 'P', 'last_name' => 'SANCHEZ', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JASTI', 'middle_name' => 'D', 'last_name' => 'LANGI', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JENNY MAE', 'middle_name' => 'CABIGAS', 'last_name' => 'SEDON', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'FRANCIS EDWARD', 'middle_name' => 'PINEDA', 'last_name' => 'LAM', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'CRISTINA', 'middle_name' => 'LADERO', 'last_name' => 'CALIZO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'WINZEN', 'middle_name' => 'G', 'last_name' => 'PACALDO', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => '']);
    User::create(['first_name' => 'Renee Boy', 'middle_name' => 'M', 'last_name' => 'Binondo', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'Mikko', 'middle_name' => 'P', 'last_name' => 'Insao', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'Kenneth Joyce', 'middle_name' => 'A', 'last_name' => 'Cordova', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'FLEMAR', 'middle_name' => 'G', 'last_name' => 'PAGSAC', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'SETH JASPER', 'middle_name' => 'A', 'last_name' => 'NAPALIT', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MIE', 'middle_name' => 'A', 'last_name' => 'BAÃ‘ADOS', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'CRISTOPHER', 'middle_name' => 'C', 'last_name' => 'MATILDO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MICHELLE', 'middle_name' => 'P', 'last_name' => 'ABUDA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JARIND MAE', 'middle_name' => 'VILLANUEVA', 'last_name' => 'ALCALA', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'JOHN LEO', 'middle_name' => 'O.', 'last_name' => 'ESTACIO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'XANDRA MAY', 'middle_name' => 'B.', 'last_name' => 'FAUTA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'CHARISSE MAE', 'middle_name' => 'C.', 'last_name' => 'FELISILDA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JOSEPH', 'middle_name' => 'B.', 'last_name' => 'FONTANARES', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'DOMINIQUE', 'middle_name' => 'R.', 'last_name' => 'FUENTES', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'UZZIEL JOHN', 'middle_name' => 'V.', 'last_name' => 'GALAGATE', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'AZIS MAISAH', 'middle_name' => 'C.', 'last_name' => 'HADJI', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'DATU ADNAN', 'middle_name' => 'S.', 'last_name' => 'IBRAHIM', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JOHNMAR', 'middle_name' => 'O.', 'last_name' => 'JIHAN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'LYNN', 'middle_name' => 'S.', 'last_name' => 'LANUGON', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MERRY JOY', 'middle_name' => 'C.', 'last_name' => 'LICERA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MARIANETTE', 'middle_name' => 'T.', 'last_name' => 'LOREJO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'HERMIE', 'middle_name' => 'M.', 'last_name' => 'MAYORMITA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'RHEA JANE', 'middle_name' => 'C.', 'last_name' => 'ANGGOY', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'UZZIEL JEAN', 'middle_name' => 'B.', 'last_name' => 'PARAN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MARGIE', 'middle_name' => 'J.', 'last_name' => 'PARLINGAYAN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'CAMILLE', 'middle_name' => 'S.', 'last_name' => 'RESPEROS', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'JERSON', 'middle_name' => 'DUMAAN', 'last_name' => 'SOLON', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'JADE', 'middle_name' => 'L.', 'last_name' => 'VALDEZ', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'RIZALDE', 'middle_name' => 'PENACO', 'last_name' => 'VALENDEZ', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'FLORIE ANN', 'middle_name' => 'B.', 'last_name' => 'VILLARINO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'CHERRY JANE', 'middle_name' => 'ABELLA', 'last_name' => 'GOMEZ', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'CHRISTINE MAE', 'middle_name' => 'Z', 'last_name' => 'ANDRADE', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MARIA BRITA', 'middle_name' => 'P', 'last_name' => 'RIVERA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JAIME', 'middle_name' => 'JALANDONI', 'last_name' => 'ARELLANO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'GIN PARKY', 'middle_name' => 'DELLOMES', 'last_name' => 'ESCALADA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'KING JON', 'middle_name' => 'MANUEL', 'last_name' => 'GANERON', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ARGIE', 'middle_name' => '', 'last_name' => 'TERANTE', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'CLAIRE NHIL', 'middle_name' => 'DIAZ', 'last_name' => 'TIBAY', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'RUSSJUN', 'middle_name' => 'SANCHEZ', 'last_name' => 'BUCIO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'LOVE BRIX', 'middle_name' => 'ASTROLOGO', 'last_name' => 'CATEDRILLA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'SHEENA MAE', 'middle_name' => 'LAPAZ', 'last_name' => 'DAYANAN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'GALIAH', 'middle_name' => 'ESTOQUE', 'last_name' => 'CASAS', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'MERAZON', 'middle_name' => 'SALIPOT', 'last_name' => 'RONCALES', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'AYESHA', 'middle_name' => 'NOVINO', 'last_name' => 'TORDILLO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'SHIHAN MARIE CHESKA', 'middle_name' => 'AMBAY', 'last_name' => 'ALEJO', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'JAMES', 'middle_name' => 'LABAYEN', 'last_name' => 'SUAREZ', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'KOJI IAN', 'middle_name' => 'N/A', 'last_name' => 'BINCOY', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MARJORIE MAY', 'middle_name' => 'N/A', 'last_name' => 'DESAMITO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MARICAR', 'middle_name' => 'ARZAGA', 'last_name' => 'GONZALES', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JEMMAR', 'middle_name' => 'ANTIQUINA', 'last_name' => 'GALACIO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'KENT', 'middle_name' => 'MARGALLO', 'last_name' => 'LASMARIAS', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'VINA', 'middle_name' => 'M', 'last_name' => 'JOVEN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JESSA MAE', 'middle_name' => 'ELTAGONDE', 'last_name' => 'VILLAFUERTE', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ULISA JOY', 'middle_name' => 'MOLIJON', 'last_name' => 'ULGASAN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JAN DEL', 'middle_name' => 'BONIAO', 'last_name' => 'OMANDAM', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ROXAN', 'middle_name' => 'REYES', 'last_name' => 'CAÃ‘ETE', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MARILOU', 'middle_name' => 'MADJUS', 'last_name' => 'SINGCO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'LOUIS TOM', 'middle_name' => '', 'last_name' => 'RAMINTAS', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'BREN MAE', 'middle_name' => 'BALDERAS', 'last_name' => 'ALAMBATIN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'APRIL ELLA', 'middle_name' => 'CARAMUNGAN', 'last_name' => 'ASUNCION', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JENNYLYN', 'middle_name' => 'PARCON', 'last_name' => 'CLAVE', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'GRACE ELAINE MAE', 'middle_name' => 'REMPILLO', 'last_name' => 'GUMIA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JOYSON', 'middle_name' => 'TORRENO', 'last_name' => 'CONCEPCION', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JAMAICA', 'middle_name' => 'S', 'last_name' => 'BARREDO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'KARETH ANTHONY', 'middle_name' => 'CASTILLO', 'last_name' => 'REMIGIO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ARIEL', 'middle_name' => 'PEPANIA', 'last_name' => 'LEONO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'REPONTE', 'middle_name' => 'LIWANTA', 'last_name' => 'GUNTINAS', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'NIEL FE GRACE', 'middle_name' => 'GALINATO', 'last_name' => 'JONTILLA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'NEILCY GAY', 'middle_name' => 'RUBINO', 'last_name' => 'JAVILLES', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'AIZA MAE', 'middle_name' => 'LIWAWAS', 'last_name' => 'ENAD', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ROCKY LEO', 'middle_name' => 'CASIÑO', 'last_name' => 'CALO', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'DANILO II', 'middle_name' => 'PESCANTE', 'last_name' => 'CUBELO', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'BONIFACIO III', 'middle_name' => 'PARPAN', 'last_name' => 'ADORMEO', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'DIVINE GRACE', 'middle_name' => 'G', 'last_name' => 'DAYRIT', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JAN ROYCE', 'middle_name' => 'B', 'last_name' => 'BARRETE', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'DIANE LORAINE', 'middle_name' => 'B', 'last_name' => 'GULTIA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'PERCIVAL GLEN', 'middle_name' => 'L', 'last_name' => 'PALABRICA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JOBERLYN', 'middle_name' => 'T', 'last_name' => 'JUARIO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'HESSAN BASRIE', 'middle_name' => 'L', 'last_name' => 'ACLIM', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'RIZA', 'middle_name' => '', 'last_name' => 'DE LEON', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'LADY MARY ANNE', 'middle_name' => '', 'last_name' => 'CALUBAG', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'HONELYN', 'middle_name' => 'BERCO', 'last_name' => 'BRIONES', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'LEONIDES', 'middle_name' => 'ACEVEDO', 'last_name' => 'SALINAS', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'HAROLD NICK', 'middle_name' => 'ROZ', 'last_name' => 'ASCAREZ', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ALJON', 'middle_name' => 'TABLINGON', 'last_name' => 'SAMBOGOY', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JAN EMMANUEL', 'middle_name' => 'GASTA', 'last_name' => 'PANUNCIA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'FATIMA', 'middle_name' => 'DELA CRUZ', 'last_name' => 'GALLETO', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'MARIA THERESA', 'middle_name' => 'PERTIMOS', 'last_name' => 'SUAN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ELVIE JOY', 'middle_name' => 'SABERON', 'last_name' => 'RABECA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'RENE MATTHEW', 'middle_name' => 'BONSUBRE', 'last_name' => 'GUERRA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'DARELL', 'middle_name' => 'MIGUEL', 'last_name' => 'CURATIVO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'NEFTALI', 'middle_name' => 'PACLIBAR', 'last_name' => 'OQUIAS', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'NIKKO', 'middle_name' => 'SUPERAL', 'last_name' => 'DANO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JUDE', 'middle_name' => 'LIAD', 'last_name' => 'ESTRELLA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'RENZ', 'middle_name' => 'SANGIL', 'last_name' => 'MANZALA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JUVY', 'middle_name' => 'BABANTO', 'last_name' => 'BARQUILLA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'RHEAN MAE', 'middle_name' => 'CANTAÑERO', 'last_name' => 'ALCOVER', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JESUS', 'middle_name' => 'BARBA', 'last_name' => 'RAMIREZ', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'RIZA FLOR', 'middle_name' => 'MANCHA', 'last_name' => 'LEPARTO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'LUCENA', 'middle_name' => 'ESTEBAN', 'last_name' => 'TEMPLA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'HONEY JEAN', 'middle_name' => 'ALCOBER', 'last_name' => 'LAURENTE', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'INDIRA', 'middle_name' => 'MASAGLANG', 'last_name' => 'MUSA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'KIM CHIELO', 'middle_name' => 'LARUYA', 'last_name' => 'FEBRIA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'KIRBY', 'middle_name' => '', 'last_name' => 'GUDMALIN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ANGELIE', 'middle_name' => '', 'last_name' => 'VILLACOTE', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JOHNREY', 'middle_name' => 'CORNILLOS', 'last_name' => 'GARNICA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ASNAIDA', 'middle_name' => 'ALI', 'last_name' => 'SAPAL', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MARCHELY', 'middle_name' => 'BACALSO', 'last_name' => 'ESTANDARTE', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'EMMANUEL', 'middle_name' => 'FERNANDEZ', 'last_name' => 'CAPUTOL', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'BLESSIE', 'middle_name' => 'CAMISA', 'last_name' => 'QUITARA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JOHN ARNEI', 'middle_name' => 'BASA', 'last_name' => 'ISAGA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'SEDRIC SHERWEN', 'middle_name' => 'FEDILLAGA', 'last_name' => 'CASTOR', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'RAM', 'middle_name' => 'NISNISAN', 'last_name' => 'SEMPRON', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JOHN MARK', 'middle_name' => 'BATOY', 'last_name' => 'GUANZON', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'VIVINA', 'middle_name' => 'MALASARTE', 'last_name' => 'ALBINDA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'VICENTE', 'middle_name' => 'PALMERA', 'last_name' => 'MONTESCLAROS', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JOLINA', 'middle_name' => 'IBNO', 'last_name' => 'MISUARI', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'ANGEL FATE', 'middle_name' => 'SABIJON', 'last_name' => 'PADILLA', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'ART JOHN', 'middle_name' => 'MASLOG', 'last_name' => 'MASINADIONG', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'RESTY', 'middle_name' => 'CUTAY', 'last_name' => 'COSTAN', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'JOHN LLOYD', 'middle_name' => 'SALCEDO', 'last_name' => 'BAUTISTA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'YASMIN GRACE', 'middle_name' => 'BOLORAN', 'last_name' => 'FORONES', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JESSA MAE', 'middle_name' => 'CORONADO', 'last_name' => 'BULAGAO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'HANNAH BIANCA', 'middle_name' => '', 'last_name' => 'PEÑANUEVA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'SHAIRA', 'middle_name' => 'SULIMAN', 'last_name' => 'UDIN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'NOVEE MAE', 'middle_name' => 'BABATU-AN', 'last_name' => 'ADLAWAN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JANELECT', 'middle_name' => 'MERCADO', 'last_name' => 'CAVAN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JOVANNI', 'middle_name' => 'LAGAR', 'last_name' => 'PAMUGAS', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'WINSTON REY', 'middle_name' => 'LEGASPI', 'last_name' => 'RONCALES', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ROLANDO', 'middle_name' => 'TECSON', 'last_name' => 'AMORIN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'GEOFFREY', 'middle_name' => 'DELAS ALAS', 'last_name' => 'VICENTE', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'KIMMY', 'middle_name' => 'MONTOJO', 'last_name' => 'BASACA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'PAUL JUCO', 'middle_name' => 'PLAZA', 'last_name' => 'RICABLANCA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'GERLIE', 'middle_name' => 'MAGWALING', 'last_name' => 'TINONG', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'SHIRLETA', 'middle_name' => 'BANDICO', 'last_name' => 'CABI-AO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JOHN LESTER', 'middle_name' => 'BUCOG', 'last_name' => 'RAGAS', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'ALFREDO', 'middle_name' => 'PANTONIAL', 'last_name' => 'DUCANES', 'extension_name' => '', 'email' => '', 'gender' => 'MALE', 'civil_status' => 'MARRIED']);
    User::create(['first_name' => 'ROVIENSON', 'middle_name' => 'CAÑETE', 'last_name' => 'AMATONG', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ANCER', 'middle_name' => 'REAS', 'last_name' => 'LORENO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JAY-ANN', 'middle_name' => 'NAMION', 'last_name' => 'HABLA', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'JERECO', 'middle_name' => 'V', 'last_name' => 'ALIMOON', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'APPLE JAN', 'middle_name' => 'MABANDOS', 'last_name' => 'CABELLON', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JUVYLYN', 'middle_name' => 'DEMORAL', 'last_name' => 'NALZARO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'EVONIE', 'middle_name' => 'NASILUAN', 'last_name' => 'AMPER', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'BREDALYN', 'middle_name' => 'JORDAN', 'last_name' => 'LOLO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'KATHLEEN MAE', 'middle_name' => 'RUIZ', 'last_name' => 'MORALES', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'TARON', 'middle_name' => 'VERDADERO', 'last_name' => 'TARON', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'HANAH BEL', 'middle_name' => 'YAP', 'last_name' => 'PEDRES', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JELYN', 'middle_name' => 'LOPE', 'last_name' => 'VELASCO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JOEL', 'middle_name' => 'CAGAPE', 'last_name' => 'RELAMPAGOS', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MARIBEL', 'middle_name' => 'VOCALES', 'last_name' => 'TORRENUEVA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JAYVEE', 'middle_name' => 'LUCERO', 'last_name' => 'ESCUADRO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ALTER JOHN', 'middle_name' => 'CABESAS', 'last_name' => 'GUILLAS', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MARYCRIS', 'middle_name' => 'ANTIOLA', 'last_name' => 'LAS PIÑAS', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'RENANTE', 'middle_name' => 'VICENTE', 'last_name' => 'BOSE', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'LEA MEA', 'middle_name' => 'TIROL', 'last_name' => 'UGALDE', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'VENUS', 'middle_name' => '', 'last_name' => 'LABORTE', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'SWEAT ANDREA', 'middle_name' => 'MASAMBO', 'last_name' => 'GUARDADOS', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'KAREN MAE', 'middle_name' => 'BUTA', 'last_name' => 'DOLOR', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'CHRISTIOLA PEBIELEOES', 'middle_name' => 'VISTA', 'last_name' => 'CALIS', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'IRENE', 'middle_name' => 'YBAÑEZ', 'last_name' => 'GEVERA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'STELLA MAE', 'middle_name' => 'SOCORRO', 'last_name' => 'CANOY', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JASER', 'middle_name' => 'SAMUDLAN', 'last_name' => 'SAIGAD', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JESSA MAE', 'middle_name' => 'ALCAZAREN', 'last_name' => 'ALEO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'GEORGENE', 'middle_name' => 'UMPAD', 'last_name' => 'BIOL', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MARVIN JAY', 'middle_name' => 'LUEGA', 'last_name' => 'ESTRADA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MELANIE', 'middle_name' => 'ABELITA', 'last_name' => 'LUZANO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'LUTCHIE MAE', 'middle_name' => 'NOVABOS', 'last_name' => 'BAYOG', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JEYLORD', 'middle_name' => 'ONGCOY', 'last_name' => 'TUNGKASAN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'FRAULEIN FREYN', 'middle_name' => 'AROÑA', 'last_name' => 'PAMPILON', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'OLYFER', 'middle_name' => 'VILLARIN', 'last_name' => 'CUARTERON', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'CHRISTINE', 'middle_name' => 'CHAVEZ', 'last_name' => 'MACION', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'SUNNY', 'middle_name' => 'MANLIGUEZ', 'last_name' => 'DUMANDAN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'CHINCHIN', 'middle_name' => 'DELA CRUZ', 'last_name' => 'MABASA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ARLYN', 'middle_name' => 'DIAZ', 'last_name' => 'CUI', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'GLAIZA MAE', 'middle_name' => 'JANDOC', 'last_name' => 'TIAWIN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'GERALDINE', 'middle_name' => 'FLORES', 'last_name' => 'IBAÑEZ', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'EMMIE', 'middle_name' => 'LIM', 'last_name' => 'GALLO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'PASTORA', 'middle_name' => 'SALUDARES', 'last_name' => 'BARDOQUILLO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ANA LUZ', 'middle_name' => 'CORTEZ', 'last_name' => 'INATO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JERHAMIE', 'middle_name' => 'CABALUNA', 'last_name' => 'SUROYSUROY', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'LIEZHEL', 'middle_name' => 'LONDINA', 'last_name' => 'CAJES', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JENNYLYN', 'middle_name' => 'DAÑO', 'last_name' => 'ANQUERA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'CERINO', 'middle_name' => 'ESTRADA', 'last_name' => 'ELLO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'PIA MAE', 'middle_name' => 'TIMBAL', 'last_name' => 'MORALES', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JAYRALD', 'middle_name' => 'GULILA', 'last_name' => 'ALABADO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JESSA MAE', 'middle_name' => 'NUDALO', 'last_name' => 'TABUGOC', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'THERESE DIANNE', 'middle_name' => 'SUAREZ', 'last_name' => 'ONGAYO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'RENTY LOUISE', 'middle_name' => 'ANCAJAS', 'last_name' => 'GAZO', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'JUMSHALI ROSEZAIN', 'middle_name' => 'SABA-ANI', 'last_name' => 'LUPON', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'RHEA', 'middle_name' => '', 'last_name' => 'MABATO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MILKY FAYE', 'middle_name' => 'ALTIZO', 'last_name' => 'PAGUYAN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JAY ANN', 'middle_name' => 'URBINA', 'last_name' => 'ODALES', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JUVIGENE', 'middle_name' => 'MARIANO', 'last_name' => 'MAPAYO', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'GRACE', 'middle_name' => 'LAUDE', 'last_name' => 'CAHULOGAN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ANGELO', 'middle_name' => 'APISTAR', 'last_name' => 'ARMADA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MARY MAY', 'middle_name' => 'ABRAGAN', 'last_name' => 'BINALAY', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'REJEANN', 'middle_name' => 'ALVEZ', 'last_name' => 'ALCANTARA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MELARD', 'middle_name' => 'NALANGAN', 'last_name' => 'MANDARIAGA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'LOVELY ROSE', 'middle_name' => 'ARGUELLES', 'last_name' => 'GALON', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ROEL', 'middle_name' => 'CABUSAS', 'last_name' => 'CASIMIRO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'VENUS KYLENE', 'middle_name' => 'ANTOPINA', 'last_name' => 'BALANDRA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'KENNETH', 'middle_name' => 'MAHINAY', 'last_name' => 'DUCANES', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JOEL', 'middle_name' => 'SAYSON', 'last_name' => 'TACULIN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JULIA MAE', 'middle_name' => 'HORNIDO', 'last_name' => 'LIMOSNERO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'RAIZA EDELLIE JANE', 'middle_name' => 'MANGUILIMOTAN', 'last_name' => 'BERCO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JIM', 'middle_name' => 'ASCARES', 'last_name' => 'ALCONTIN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'FERNAN', 'middle_name' => 'CUBOL', 'last_name' => 'DALA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'RICHARD', 'middle_name' => 'GALLAZA', 'last_name' => 'TAMALA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'HANNAH KIRSTIE', 'middle_name' => 'TEEL', 'last_name' => 'NAGUITA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'LIAM IZACH', 'middle_name' => 'FLORES', 'last_name' => 'TANUAN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JELYN', 'middle_name' => 'OPPUS', 'last_name' => 'DELA CRUZ', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ADRIAN JOSE', 'middle_name' => 'PACHOCO', 'last_name' => 'CID', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MELQUE FRANCIS', 'middle_name' => 'MANIGOS', 'last_name' => 'ESTOQUIA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'NOR-AIN', 'middle_name' => 'SULTAN', 'last_name' => 'AMORAN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'PERLIE', 'middle_name' => 'AMADO', 'last_name' => 'MONTES', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'DIANA ROSE', 'middle_name' => 'S', 'last_name' => 'CAJIPE', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'IRENE', 'middle_name' => 'B', 'last_name' => 'DUMLAO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MICHAEL CHRISTOPHER', 'middle_name' => 'R', 'last_name' => 'MATHAY', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'LEO', 'middle_name' => 'L', 'last_name' => 'QUINTILLA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'YSABEL', 'middle_name' => 'N/A', 'last_name' => 'YLARDE', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'CRISTY', 'middle_name' => 'CAÑETE', 'last_name' => 'MANUEL', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'DEBBIE', 'middle_name' => 'GENELZA', 'last_name' => 'MAHILUM', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'CLAIRE ANN', 'middle_name' => 'CONSUEGRA', 'last_name' => 'PALABRICA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ROVIE LOVE JOY', 'middle_name' => 'NAVALLO', 'last_name' => 'BELAYA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JULLIE TRESHA', 'middle_name' => 'MANTILLA', 'last_name' => 'HINOGUIN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'CARL JOHN', 'middle_name' => 'DAMASO', 'last_name' => 'BUCTUAN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JUDY ANN', 'middle_name' => 'BADE', 'last_name' => 'GOLEZ', 'extension_name' => '', 'email' => '', 'gender' => 'FEMALE', 'civil_status' => 'SINGLE']);
    User::create(['first_name' => 'SHELLA JANE', 'middle_name' => 'RUELO', 'last_name' => 'ESPAÑOLA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'VANIZA', 'middle_name' => 'LAWAGON', 'last_name' => 'NAVARRO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'LUTHER', 'middle_name' => 'DIKILATO', 'last_name' => 'YPIL', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'DINDO', 'middle_name' => 'LAQUINTA', 'last_name' => 'CRUJEDO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ROSALIE', 'middle_name' => 'BESINAN', 'last_name' => 'MINGUETO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JOSEPHINE', 'middle_name' => 'CURAN', 'last_name' => 'VILLACURA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'RONA JOY', 'middle_name' => 'RIVERA', 'last_name' => 'MANGARIN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MOLINA', 'middle_name' => 'LIBRE', 'last_name' => 'BARO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'CRISTIAN PAULO', 'middle_name' => 'SURILLA', 'last_name' => 'GALLARDO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'SARAH JANE', 'middle_name' => 'DE LARA', 'last_name' => 'MANAGA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JELYKA', 'middle_name' => '', 'last_name' => 'MONTES', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ABBY JANE', 'middle_name' => 'GALLETO', 'last_name' => 'AMISOLA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'BENEDICT ANGELO', 'middle_name' => 'BAYLON', 'last_name' => 'YU', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ARIEL', 'middle_name' => 'SUELTO', 'last_name' => 'COMEGHOD', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JANIEL KEN', 'middle_name' => 'ANDAYAN', 'last_name' => 'DIGDIG', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'NOEL', 'middle_name' => 'VERANO', 'last_name' => 'MAUSISA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'SUHRIA DHYLL', 'middle_name' => 'LUGO', 'last_name' => 'URBIZTONDO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'PATRICK', 'middle_name' => 'CUIZON', 'last_name' => 'DOROPAN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'HONEY SUSIE', 'middle_name' => '', 'last_name' => 'PARAISO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'KIMBERLY', 'middle_name' => 'AGUSTIN', 'last_name' => 'BARDINAS', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'RICA ANGELIE', 'middle_name' => 'LOQUINARIO', 'last_name' => 'GAJETO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'RUWAIDA', 'middle_name' => 'BUNGCAS', 'last_name' => 'CAPARAN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JHON PIP', 'middle_name' => 'ANTOQUE', 'last_name' => 'LANGUBAN', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'AIRAH', 'middle_name' => 'TAGUINOPON', 'last_name' => 'SALGADO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ANACLETA', 'middle_name' => 'ESTIMADO', 'last_name' => 'SALAZAR', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'CHARMAINE', 'middle_name' => 'PERALTA', 'last_name' => 'TOCO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MARJORIE', 'middle_name' => 'DIGDIGAN', 'last_name' => 'PARILLA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'KRISTINE', 'middle_name' => 'NAVALES', 'last_name' => 'COMENDADOR', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'JULIET', 'middle_name' => 'GUINITA', 'last_name' => 'VIBAR', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'LINDY', 'middle_name' => 'PABLO', 'last_name' => 'FELIPE', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'NOHAINA', 'middle_name' => 'TANDIONG', 'last_name' => 'AMBANG', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MIYUKI', 'middle_name' => 'ORTEGA', 'last_name' => 'MERQUITA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'CRISTILITO', 'middle_name' => 'SALA', 'last_name' => 'ALISON', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ROSIE MAE', 'middle_name' => 'ABASTILLAS', 'last_name' => 'LASAGAS', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ROTCHELL', 'middle_name' => 'ABILA', 'last_name' => 'PELAYO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'VENUS', 'middle_name' => 'MALABARBAS', 'last_name' => 'PAJAGANAS', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'MARY JOY', 'middle_name' => 'PAGCAS', 'last_name' => 'BONGABONG', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'NICOLE GUENN', 'middle_name' => 'EVANGELISTA', 'last_name' => 'DEQUIÑA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ANDIE FLOR', 'middle_name' => 'CAÑABANO', 'last_name' => 'MAGANDAM', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'CHRISHEN DHEEL', 'middle_name' => 'VILLAMON', 'last_name' => 'DIOG', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'DONUEL', 'middle_name' => 'ACOSTA', 'last_name' => 'FUENTES', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'DARLENE CLAIRE', 'middle_name' => 'SAGUTA-ON', 'last_name' => 'MORALES', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'QUEENZELA', 'middle_name' => 'VILLANUEVA', 'last_name' => 'RODRIGUEZ', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'KENT ERROL', 'middle_name' => 'URACA', 'last_name' => 'TARAY', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ANALIE', 'middle_name' => 'DIANCO', 'last_name' => 'GUPITA', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'LARKEN', 'middle_name' => 'DIANCO', 'last_name' => 'ARCENAL', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'RAYMUND', 'middle_name' => 'REBUSA', 'last_name' => 'MACABUDBUD', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ROXANNE', 'middle_name' => 'ENRIQUEZ', 'last_name' => 'BUCAYONG', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'RONALYN MAE', 'middle_name' => 'ZOZOBRADO', 'last_name' => 'AGUILAR', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
    User::create(['first_name' => 'ROY', 'middle_name' => 'BELANO', 'last_name' => 'BUSTALEÑO', 'extension_name' => '', 'email' => '', 'gender' => '', 'civil_status' => '']);
  }
}
